-- Los esquemas cobranza y auditoria son creados por las migraciones Flyway (V001__crear_esquemas_base.sql).
-- Este script de inicialización Docker solo gestiona extensiones de PostgreSQL (ver 01_extensions.sql).
-- No crear esquemas ni tablas aquí; esa responsabilidad pertenece exclusivamente a Flyway.
