spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cobranza_db}
    username: ${POSTGRES_USER:cobranza_dev}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    enabled: true
